version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    develop:
      watch:
      - action: sync
        path: ./src
        target: /src/app
        ignore:
          - node_modules/
      - action: rebuild
        path: package.json
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: npm start

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
